### ISSUE TITLE
Improvements on install / evaluation instructions

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#1]
Right now the instructions say to use Composer and `composer create-project`. Composer will be a dependency, but should the README also state the project can be cloned or downloaded as an archive?

**Comment by mglaman** [comment]
We should instruct how users can install and run without `composer-create` project.

* Download https://github.com/drupalcommerce/demo-project/archive/master.zip
* Extract the project
* cd into project
* composer install
* composer run preview

**Comment by dwkitchen** [comment]
If they are going to have to use `composer install` they can use `composer create-project`
