### ISSUE TITLE
Need a way to only display first image value for field_images on catalog.

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#14]
<img width="902" alt="product_catalog___drupal" src="https://user-images.githubusercontent.com/3698644/36882589-5d26959a-1d9a-11e8-97ba-9e5fde0e45ce.png">

**Comment by mglaman** [comment]
Removing Backport label.. there's no code.

**Comment by bojanz** [comment]
I think we should add a commerce_demo preprocess that provides $content['catalog_image'] to the template, taken from the default variation's first image.

**Comment by mglaman** [comment]
I actually have an image formatter that let's you pick a delta. So first item only. I think this would be a better and more configurable.

**Comment by mglaman** [comment]
Fixed in https://github.com/bojanz/commerce_demo/commit/24b692f60a57e4436ccf13fce779631ebc0414b9
