### ISSUE TITLE
Changing an attribute on add to cart breaks fancy image viewer

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#21]
![drupal_commerce_hoodie___belgrade](https://user-images.githubusercontent.com/3698644/36997807-739d968c-2080-11e8-81ea-51884ef7af7b.png)

It's like during the AJAX process the view mode is lost and it kicks back to default.

Probably a Drupal Commerce bug.

**Comment by bojanz** [comment]
Didn't we fix that in Commerce -dev?

**Comment by mglaman** [comment]
Maybe, I will test. I was using latest release so it was somewhat stable.
The view mode is lost on Ajax and now I think I remember a patch coming in
for that.

**Comment by mglaman** [comment]
This is fixed w/ 2.5
