### ISSUE TITLE
Authenticated users are missing "Manage own payment methods"

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#33]
Out of the box, users cannot manage their payment methods

**Comment by bojanz** [comment]
This is fixed in Commerce -dev

**Comment by mglaman** [comment]
https://github.com/drupalcommerce/commerce/commit/0b5a3fb6093b3e76b81d29caeb4b5f65f2170e63

I need to update our demo updates.

**Comment by mglaman** [comment]
2.8 released.
