### ISSUE TITLE
Link to theme from demo?

### ISSUE THREAD

**Issue by GraphGrailAi** [drupalcommerce/demo-project#40]
Is there a link to theme used in demo to download?
And maybe a full code dump of all modules installed for drupal project - there are some issues with composer download

**Comment by bojanz** [comment]
The theme is Belgrade.
You will always need Composer, so I'm afraid there won't be a full dump. You will have to resolve your Composer issues.

**Comment by GraphGrailAi** [comment]
Solved myself - i used commerce_demo from drupal.org and https://www.drupal.org/project/belgrade  dev version (errors with stable) - than i was able to reproduce site
