### ISSUE TITLE
Demo and Belgrade breaks with Bootstrap v3.17

### ISSUE THREAD

**Issue by chri5tia** [drupalcommerce/demo-project#42]
When I installed the demo, there was no theme enabled so I enabled Belgrade, which broke the site, however, the site worked after downgrading to Bootstrap to 3.16. 

Following is the logged error after enabling Belgrade, with Bootstrap 3.17 installed:

```Error: Unsupported operand types in Drupal\bootstrap\Plugin\Provider\JsDelivr->processDefinition() (line 108 of [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Plugin/Provider/JsDelivr.php) #0 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Plugin/ProviderManager.php(38): Drupal\bootstrap\Plugin\Provider\JsDelivr->processDefinition(Array, 'jsdelivr') #1 [project_root]demo-commerce/web/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(286): Drupal\bootstrap\Plugin\ProviderManager->processDefinition(Array, 'jsdelivr') #2 [project_root]demo-commerce/web/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(175): Drupal\Core\Plugin\DefaultPluginManager->findDefinitions() #3 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Plugin/PluginManager.php(101): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() #4 [project_root]demo-commerce/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryCachedTrait.php(22): Drupal\bootstrap\Plugin\PluginManager->getDefinitions() #5 [project_root]demo-commerce/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php(59): Drupal\Core\Plugin\DefaultPluginManager->getDefinition('jsdelivr', false) #6 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(483): Drupal\Core\Plugin\DefaultPluginManager->hasDefinition('jsdelivr') #7 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Plugin/Setting/Advanced/Cdn/CdnProvider.php(60): Drupal\bootstrap\Theme->getProvider('jsdelivr') #8 [project_root]demo-commerce/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php(25): Drupal\bootstrap\Plugin\Setting\Advanced\Cdn\CdnProvider->__construct(Array, 'cdn_jsdelivr_ve...', Array) #9 [project_root]demo-commerce/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php(83): Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('cdn_jsdelivr_ve...', Array) #10 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Plugin/PluginManager.php(84): Drupal\Component\Plugin\PluginManagerBase->createInstance('cdn_jsdelivr_ve...', Array) #11 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(554): Drupal\bootstrap\Plugin\PluginManager->createInstance('cdn_jsdelivr_ve...') #12 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/ThemeSettings.php(56): Drupal\bootstrap\Theme->getSettingPlugin() #13 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(750): Drupal\bootstrap\ThemeSettings->__construct(Object(Drupal\bootstrap\Theme)) #14 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(532): Drupal\bootstrap\Theme->settings() #15 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(186): Drupal\bootstrap\Theme->getSetting('schemas') #16 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Bootstrap.php(490): Drupal\bootstrap\Theme->__construct(Object(Drupal\Core\Extension\Extension), Object(Drupal\Core\Extension\ThemeHandler)) #17 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(359): Drupal\bootstrap\Bootstrap::getTheme('bootstrap', Object(Drupal\Core\Extension\ThemeHandler)) #18 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(765): Drupal\bootstrap\Theme->getAncestry() #19 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Theme.php(182): Drupal\bootstrap\Theme->subthemeOf('bootstrap') #20 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Bootstrap.php(490): Drupal\bootstrap\Theme->__construct(Object(Drupal\Core\Extension\Extension), Object(Drupal\Core\Extension\ThemeHandler)) #21 [project_root]demo-commerce/web/themes/contrib/bootstrap/src/Bootstrap.php(1049): Drupal\bootstrap\Bootstrap::getTheme() #22 [project_root]demo-commerce/web/themes/contrib/bootstrap/bootstrap.theme(31): Drupal\bootstrap\Bootstrap::initialize() #23 [project_root]demo-commerce/web/core/lib/Drupal/Core/Extension/Extension.php(145): include_once('/Applications/A...') #24 [project_root]demo-commerce/web/core/themes/engines/twig/twig.engine(35): Drupal\Core\Extension\Extension->load() #25 [internal function]: twig_init(Object(Drupal\Core\Extension\Extension)) #26 [project_root]demo-commerce/web/core/lib/Drupal/Core/Theme/ThemeInitialization.php(144): call_user_func('twig_init', Object(Drupal\Core\Extension\Extension)) #27 [project_root]demo-commerce/web/core/lib/Drupal/Core/Theme/ThemeInitialization.php(74): Drupal\Core\Theme\ThemeInitialization->loadActiveTheme(Object(Drupal\Core\Theme\ActiveTheme)) #28 [project_root]demo-commerce/web/core/lib/Drupal/Core/Theme/ThemeManager.php(406): Drupal\Core\Theme\ThemeInitialization->initTheme('belgrade') #29 [project_root]demo-commerce/web/core/lib/Drupal/Core/Theme/ThemeManager.php(96): Drupal\Core\Theme\ThemeManager->initTheme(Object(Drupal\Core\Routing\RouteMatch)) #30 [project_root]demo-commerce/web/core/lib/Drupal/Core/Render/ElementInfoManager.php(74): Drupal\Core\Theme\ThemeManager->getActiveTheme() #31 [project_root]demo-commerce/web/core/lib/Drupal/Core/Form/FormBuilder.php(810): Drupal\Core\Render\ElementInfoManager->getInfo('form') #32 [project_root]demo-commerce/web/core/lib/Drupal/Core/Form/FormBuilder.php(276): Drupal\Core\Form\FormBuilder->prepareForm('system_themes_a...', Array, Object(Drupal\Core\Form\FormState)) #33 [project_root]demo-commerce/web/core/lib/Drupal/Core/Form/FormBuilder.php(216): Drupal\Core\Form\FormBuilder->buildForm('system_themes_a...', Object(Drupal\Core\Form\FormState)) #34 [project_root]demo-commerce/web/core/modules/system/src/Controller/SystemController.php(322): Drupal\Core\Form\FormBuilder->getForm('Drupal\\system\\F...', Array) #35 [internal function]: Drupal\system\Controller\SystemController->themesPage() #36 [project_root]demo-commerce/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #37 [project_root]demo-commerce/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #38 [project_root]demo-commerce/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #39 [project_root]demo-commerce/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #40 [project_root]demo-commerce/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #41 [project_root]demo-commerce/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #42 [project_root]demo-commerce/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #43 [project_root]demo-commerce/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #44 [project_root]demo-commerce/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #45 [project_root]demo-commerce/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #46 [project_root]demo-commerce/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #47 [project_root]demo-commerce/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #48 [project_root]demo-commerce/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #49 [project_root]demo-commerce/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #50 [project_root]demo-commerce/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #51 {main}.```

**Comment by chri5tia** [comment]
I would be willing to help fix this if someone points me in the right direction.

**Comment by mglaman** [comment]
What version of PHP do you have locally? Can you also post this to the Bootstrap theme queue?

**Comment by bojanz** [comment]
Looks like this was fixed in Bootstrap -dev but no release has been made yet: https://www.drupal.org/project/bootstrap/issues/3027569

**Comment by chri5tia** [comment]
I've tried in on PHP 7.0, 7.1 and 7.2. A quickfix would be to build the dependencies for this project around Bootstrap version 3.16 until 3.18 comes out. This way, Belgrade and the other themes will work and the site will work when people install the demo.

**Comment by mglaman** [comment]
We can add a conflict entry for now in the composer.json

**Comment by dwkitchen** [comment]
Outdated
