### ISSUE TITLE
Installation hitch: Stalls as "Updating dependencies"

### ISSUE THREAD

**Issue by dagny099** [drupalcommerce/demo-project#44]
Greetings,

After reading mglaman's clear and concise on how users can install and run without composer-create project, I executed steps 1-3 below but my system stalls on step #4: composer install. ... Looks like not all the dependencies are able to be installed? I'm surely overlooking something and would appreciate any help. Thanks.

> 1. Download https://github.com/drupalcommerce/demo-project/archive/master.zip ... Me: Ok!
> 2. Extract the project .... Me: Ok!
> 3. cd into project .... Me: Ok! 
> *4. composer install ... Me: EEP. Wtf?

**Sample output:**
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Killed

Running Debian 9

**Comment by ytsurk** [comment]
This means your php process went out of memory. You can try adding:

**-d memory_limit=-1**, like

`php -d memory_limit=-1 composer install`
