### ISSUE TITLE
No pictures on the product pages

### ISSUE THREAD

**Issue by TecMaWi** [drupalcommerce/demo-project#45]
Hi I've installed the demo with Composer and so far runs quite well.

Unfortunately, no images are displayed on the product pages on the left site.
Example:
/product/adventure-begins-camping-mug

The header of the image field, if activated, but already.

Can you help?
![no-productimage](https://user-images.githubusercontent.com/57140316/67769731-49460300-fa55-11e9-9401-e3045ad2643d.jpg)

**Comment by mike918** [comment]
I also have this issue on my Belgrade demo site.

However, I've noticed the issue only occurs when I'm logged in as User 1 or the user logged in has the 'Administrator' role applied.

I'm using: 
Drupal 8.7.8 
Commerce 8.x-2.14 
Belgrade 8.x-1.0-beta5
PHP 7.1.23

**Comment by mike918** [comment]
Just to add the theme looks fantastic.

**Comment by dwkitchen** [comment]
Can't reproduce
