### ISSUE TITLE
Drupal 9

### ISSUE THREAD

**Issue by ytsurk** [drupalcommerce/demo-project#56]
Do you have any plans to update this demo-project to Drupal 9?

**Comment by bradjones1** [comment]
See https://github.com/drupalcommerce/demo-project/pull/55

Per Slack:

> @mglaman  6:37 AM
> @jsacksick FYI these 3 PRs unblock this other one so the demo is D9 ready

- https://github.com/drupalcommerce/demo_commerce/pull/5
- https://github.com/drupalcommerce/demo_commerce/pull/3
- https://github.com/drupalcommerce/demo_commerce/pull/4

**Comment by ytsurk** [comment]
Alright - this may seem to work, but fe. commerce_demo and belgrad is still 8.x-1.x .. I would love to have them updated.

I already tried this upgrade path (from https://www.centarro.io/blog/how-build-drupal-commerce-development-environment), but ended up in errors with cart flyout ...

So - I think more of a feature request then - where everything is bumped and in sync .. ;) It's kind of a jungle for uninitiated.
This could be the direction for belgrade 2.0 with commerce_demo 1.0 https://github.com/drupalcommerce/demo_commerce/issues/6

This goes more into the direction of

https://www.drupal.org/project/commerce_demo/issues/3219571
https://www.drupal.org/project/commerce_demo/issues/3178881

(The centarro demo still runs on Drupal 8 though - there is a month left ;))
In https://react.demo.centarro.io the payment process is broken.

commerce_demo:^2.0-dev seams to be intended for decoupled? https://www.drupal.org/project/commerce_demo/issues/3120844

**Comment by ytsurk** [comment]
Better to use kickstart: https://github.com/centarro/commerce-kickstart-project
