### ISSUE TITLE
Broken Project

### ISSUE THREAD

**Issue by ghost** [drupalcommerce/demo-project#71]
Please, delete the thread.

And provide normal deployment instructions.

**Comment by kazimir-lyshchynski** [comment]
Debian stable, PHP 8.3

Can someone suggest, how to fix the problem?

**Comment by bojanz** [comment]
From the error message that you posted:
```
- drupal/commerce[2.17.0, ..., 2.33.0] require ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
    - drupal/commerce[2.34.0, ..., 2.x-dev] require php ^8.0 -> your php version (7.3; overridden via config.platform, actual: 8.3.6) does not satisfy that requirement.
    - ```

**Comment by bojanz** [comment]
1) Your error message is saying that you're lacking the bcmath extension
2) Looks like https://github.com/drupalcommerce/demo-project/blob/master/composer.json#L27 needs to be removed from composer.json, as it's overriding your actual PHP version with one that is too low.

**Comment by kazimir-lyshchynski** [comment]
Yes, `php8.3-bcmath` package solves the problem, but in general problem
remains the same.

**Comment by kazimir-lyshchynski** [comment]
BTW, next script will work

```sh
composer create-project -s dev centarro/commerce-kickstart-project kickstart
cd kickstart
composer require drupal/commerce_demo:^3.0
composer require 'drupal/smtp:^1.2'
cd ..
```
