### ISSUE TITLE
Move social menu config to Belgrade theme

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#9]
The `system.menu.social.yml` and `block.block.belgrade_social.yml` config should be moved from `demo_commerce` and actually in the Belgrade theme.

Just need to open issue on Drupal.org and a patch.

**Comment by bojanz** [comment]
Should a theme be providing social media blocks? It smells more like the job for the profile / demo module.

**Comment by mglaman** [comment]
Well the mocks have specific theming. And I know we're treating it as a demo theme. So it is that grey area.

But having the block and menu place allows people to just add their links and be done.
